version: '3.8'

services:
  lb-mock-aws:
    image: nginx:alpine
    container_name: lb-mock-aws
    ports:
      - "8081:80"
    # TODO: Mount the aws.html to the Nginx index page volume path
    # volumes:
    #   - ./aws.html:/usr/share/nginx/html/index.html
    restart: always

  lb-mock-gcp:
    image: nginx:alpine
    container_name: lb-mock-gcp
    ports:
      - "8082:80"
    # TODO: Mount the gcp.html to the Nginx index page volume path
    # volumes:
    #   - ./gcp.html:/usr/share/nginx/html/index.html
    restart: always

  gtm-edge-dns:
    image: haproxy:alpine
    container_name: gtm-edge-dns
    ports:
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - lb-mock-aws
      - lb-mock-gcp
    restart: always
